### PR TITLE
Using max_id query param to download much more of a user's TL

### PR DESCRIPTION
**Pull request by rdlester**
The official twitter limits are 200 tweets per user_timeline query, but 3200 accessible tweets in total. This PR will handle obtaining the additional 3000 past the first query.

### CODE REVIEW

**Comment by amanda** [comment]
this is great, thank you!

**Comment by amanda** [comment]
Hey so I tried it but it didn't work, did you test it? I just tried it out with one of the bots and got a 429 (Too Many Requests), Rate limit exceeded :'(

**Comment by amanda** [comment]
I reverted it back to the working version for now but if we can figure out how to get more tweets that would be awesome.

**Comment by rdlester** [comment]
I did test. The rate limit for statuses/user_timeline is 180 requests per 15 minutes, and since my update should make at most 16 requests, it shouldn't be an issue.

A potential problem is that `ebook` is re-downloading all the tweets every time it wants to generate a new tweet. If this happens enough in a single 15min window, it'll hit the rate limit and error out. I can make an update to cache the collected tweets that might help things out on your end.

**Pull request merged**
